"""Even Fibonacci numbers
   Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""


def is_even(n):
    return 1 if n % 2 == 0 else 0


# The sum of a Fibonacci sequence, with a cutoff value and condition
def fib_sum(f1, f2, cutoff, condition):
    sum_ = condition(f1)*f1 + condition(f2)*f2
    f3 = f1 + f2
    while f3 < cutoff:

        # if f3 fits condition, add it to sum
        sum_ = sum_ + condition(f3)*f3
        # shift f1 and f2
        f1 = f2
        f2 = f3
        # calculate next f3
        f3 = f1 + f2

    return sum_


print(fib_sum(1, 2, 4000000, is_even))

